apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - backup.yaml
  - mariadb.yaml
  - maxscale-httproute.yaml
  - maxscale.yaml
  - physicalbackup-snap.yaml
  - physicalbackup.yaml
  - sealedsecret.yaml
